sudo: required
services:
  - docker
language: python
python:
  - "3.5"
before_install:
  - docker build -f .dockerfile -t foundations/xenial:v3 --env PRNUMBER=$TRAVIS_PULL_REQUEST .
script:
  - docker run --detach=false foundations/xenial:v3 /bin/sh -c "cd /root/code; tox"
