# barry@ubuntu.com 2016-07-05 What's going on here?
#
# Because we're targetting ubuntu-image for Ubuntu 16.04 LTS (Xenial Xerus) we
# want to make sure that the test suite is running in as close to that
# environment as possible.  However, by default, Travis CI runs Python code in
# a virtualenv, pulling in dependencies from PyPI.  That's bad because we're
# only guaranteeing compatibility with archive packages, which of course may
# be different in lots of subtle ways from PyPI versions.
#
# Therefore, we use a .dockerfile that starts with the official Ubuntu Xenial
# image, installs all the test dependencies from archive packages, and then
# clones the master branch of the origin repository.

sudo: required
services:
  - docker
language: python
python:
  - "3.5"
before_install:
  - docker build -f .dockerfile -t foundations/xenial:v3 .
script:
  - /usr/bin/python3.5 .script
