sudo: required
services:
  - docker
language: python
python:
  - "3.5"
before_install:
  - docker build -f .dockerfile -t foundations/xenial:v1 .
script:
  - docker run --detach=false foundations/xenial:v1 /bin/sh -c "cd /root/ubuntu-image; tox"
